name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Jest
        uses: actions/setup-node@v1 # This is the action
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
