name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Jest
      - uses: stefanoeb/jest-action@1.0.3 # This is the action
        with:
          jestArgs: ./app.test.js
