name: Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Jest
        uses: actions/setup-node@v1 # This is the action
        with:
          node-version: "16"
      - run: npm install
      - run: npm test
